name: test github action
on: [push]
jobs:
  build-projects:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: install node modules
        run: yarn
      - name: Building React App
        run: yarn build
      - name: Building React App
        run: yarn build
      - name: Sets vercel Env
        run: |
          cd build
          mkdir .vercel
          cd .vercel
          touch project.json
          echo '{"orgId":"kEFplssM2cSZbDubOz3PTlyn","projectId":"prj_eDNaVHXKXwwaLYSfVNWuHHZhKzSf"}' > project.json
      - name: Deploying the project
        run: yarn deploy

      