name: test github action
on: [push]
jobs:
  build-and-deploy-app:
    runs-on: ubuntu-latest
    env:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: install node modules
        run: yarn
      - name: Building React App
        run: yarn build
      - name: Sets vercel Env
        run: |
          cd build
          mkdir .vercel
          cd .vercel
          touch project.json
          echo '{\"$VERCEL_ORG_ID\":"kEFplssM2cSZbDubOz3PTlyn",\"$VERCEL_PROJECT_ID\":"prj_eDNaVHXKXwwaLYSfVNWuHHZhKzSf"}' > project.json
      - name: Deploying the project
        run: yarn deploy
  test-app:
    needs: build-and-deploy-app #will wait until the build-and-deploy-app done
    runs_on: ubuntu latest
    steps:
      - run: echo "Hello!"